replicaCount: 2

image:
  repository: ahmad3740/nodejs-app # IMPORTANT: Change ahmad3740 to your actual Docker Hub username!
  tag: "23f33a2b0735766c242503a84e26de3e2768d425"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5006
