replicaCount: 2

image:
  repository: ahmad3740/nodejs-app # IMPORTANT: Change ahmad3740 to your actual Docker Hub username!
  tag: "068fc620c9baad91df174f9f628a2b5d68436bd5"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5006
