apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
  labels:
    app: nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: ahmad3740/nodejs-app:f318dda1f8a1c99cd4fb8a5e8586ab3c24e1dede
        ports:
        - containerPort: 5006
