apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
  labels:
    app: nodejs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: ahmad3740/nodejs-app:1c7eb19d6840b3122e3fadef27007561d1f2df70
        ports:
        - containerPort: 5006
